import express from 'express';
import {
  getStoryPrompt,
  getStoryFeedback,
  getSpeakingTurn,
  getSpeakingSummary,
  getFillBlanks,
  checkFillBlanks,
  getQuickTest,
  checkQuickTest,
  getPassage,
  evaluateFluency,
  getSpeakingFeedback
} from '../controllers/learnController.js';

const router = express.Router();

// Learning endpoints - all dynamically generated by Gemini
router.post('/learn/story-prompt', getStoryPrompt);           // Generate conversation prompt with role
router.post('/learn/speaking-turn', getSpeakingTurn);         // Continue conversation with corrections
router.post('/learn/speaking-summary', getSpeakingSummary);   // Analyze full session
router.post('/learn/story-feedback', getStoryFeedback);       // Evaluate user's story (legacy)
router.post('/learn/fill-blanks/new', getFillBlanks);         // Generate fill-blanks exercise
router.post('/learn/fill-blanks/check', checkFillBlanks);     // Check fill-blanks answers
router.post('/learn/quick-test/new', getQuickTest);           // Generate quick MCQ test
router.post('/learn/quick-test/check', checkQuickTest);       // Check quick test answers
router.post('/learn/passage', getPassage);                    // Generate reading passage for fluency
router.post('/learn/fluency', evaluateFluency);               // Evaluate reading fluency
router.post('/learn/speaking-feedback', getSpeakingFeedback); // Analyze speaking quality for Speak & Story

export default router;
